### ISSUE TITLE
Unable to start bot

### ISSUE THREAD

**Issue by romanpeters** [DevOps-Utrecht/bot#6]
Previously starting the bot would give me an `ImportError`. This has been fixed since 17b5bce89fc8aea178d41cf966a729e6310288c4, however, I now get a different error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/start", line 11, in <module>
    load_entry_point('devbot==0.0.2', 'console_scripts', 'start')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/devbot-0.0.2-py3.6.egg/devbot/bot.py", line 20, in <module>
    @CLIENT.event
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord.py-0.16.12-py3.6.egg/discord/client.py", line 873, in event
    raise ClientException('event registered must be a coroutine function')
discord.errors.ClientException: event registered must be a coroutine function
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1046be358>
```

**Comment by romanpeters** [comment]
Nevermind, the API key I used was incorrect.
